# Generated by Django 2.2.5 on 2020-02-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcare',
            name='customuser_ptr',
        ),
        migrations.DeleteModel(
            name='DataScientist',
        ),
        migrations.DeleteModel(
            name='HealthCare',
        ),
    ]
