# Generated by Django 2.2.5 on 2020-07-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('D', 'DATA_SCIENTIST'), ('H', 'HEALTH_CARE')], max_length=50),
        ),
    ]
