# Generated by Django 2.2.5 on 2020-02-07 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200207_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_dataScientist',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_healthCare',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('D', 'DATA_SCIENTIST'), ('H', 'HEALTH_CARE')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
