# Generated by Django 2.2.5 on 2020-02-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200207_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('D', 'DATA_SCIENTIST'), ('A', 'ADMIN'), ('H', 'HEALTH_CARE')], max_length=50),
        ),
    ]
