# Generated by Django 2.2.5 on 2020-06-02 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNNModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('normalize_mean', models.FloatField(default=None)),
                ('normalize_std', models.FloatField(default=None)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('output_dict', models.CharField(default=None, max_length=2000, null=True)),
                ('model_path', models.CharField(default=None, max_length=500)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.DATASET_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
