# Generated by Django 2.2.5 on 2020-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnnmodel',
            name='output_dict',
            field=models.CharField(default=None, max_length=2500, null=True),
        ),
    ]
