# Generated by Django 2.2.5 on 2020-06-11 18:37

from django.db import migrations, models
import modelos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20200611_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnnmodel',
            name='input_shape',
            field=models.CharField(default='50, 50, 3', max_length=30, validators=[modelos.validators.check_output_tuple]),
        ),
        migrations.AlterField(
            model_name='cnnmodel',
            name='output_dict',
            field=models.CharField(default="{'class1' : 0, 'class2': 1}", error_messages={'required': 'Please pass a dictionary in this format: {"class1": 0, "class2" : 1}'}, max_length=2500, validators=[modelos.validators.check_output_dict]),
        ),
    ]
