# Generated by Django 2.2.5 on 2020-06-11 18:37

from django.db import migrations, models
import modelos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20200611_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnnmodel',
            name='input_shape',
            field=models.CharField(default='50, 50, 3', max_length=30, validators=[modelos.validators.check_output_tuple]),
        ),
    ]
