
#THIS CLASS HAVE CONSTANT STRINGS THAT I USE ON PROJECT --> LIKE NAME OF GROUPS, PERMISSIONS, AND SO ON

#GROUPS
DATASCIENTIST_GROUP = "DS_GROUP"
HEALTH_CARE_GROUP = "HC_GROUP"

#TYPES OF USERS
ADMIN = "ADMIN"
DATASCIENTIST = "DATA_SCIENTIST"
HEALTHCARE = "HEALTH_CARE"

#APPLICATIONS
DATASET = "Dataset"

#PERMISSIONS
ADD_DATASET = "Can add dataset"
CHANGE_DATASET = "Can change dataset"
DELETE_DATASET = "Can delete dataset"
VIEW_DATASET = "Can view dataset"