
#THIS CLASS HAVE CONSTANT STRINGS THAT I USE ON PROJECT --> LIKE NAME OF GROUPS, PERMISSIONS, AND SO ON

#GROUPS
DATASCIENTIST_GROUP = "Data_Scientist"
HEALTH_CARE_GROUP = "Health_Care_Professional"

#APPLICATIONS
DATASET = "Dataset"

#PERMISSIONS
ADD_DATASET = "Can add dataset"
CHANGE_DATASET = "Can change dataset"
DELETE_DATASET = "Can delete dataset"
VIEW_DATASET = "Can view dataset"