
#THIS CLASS HAVE CONSTANT STRINGS THAT I USE ON PROJECT --> LIKE NAME OF GROUPS, PERMISSIONS, AND SO ON

#GROUPS
DATASCIENTIST_GROUP = "Data_Scientist"
HEALTH_CARE_GROUP = "Health_Care_Professional"

#TYPES OF USERS
ADMIN = "ADMIN"
DATASCIENTIST = "DATA_SCIENTIST"
HEALTHCARE = "HEALTH_CARE"

#APPLICATIONS
DATASET = "Dataset"

#PERMISSIONS
ADD_DATASET = "Can add dataset"
CHANGE_DATASET = "Can change dataset"
DELETE_DATASET = "Can delete dataset"
VIEW_DATASET = "Can view dataset"

#URLS
LOGOUT_REDIRECT_URL = '/home'
LOGIN_REDIRECT_URL = '/info'

#USER ATTRIBUTES
USERNAME = "username"
FIRST_NAME = "first_name"
LAST_NAME = "last_name"
USERTYPE = "userType"
EMAIL = "email"
PASSWORD = "password"

#MENSAGENS DE ERRO
ERROR_FORM_UPDATE_USER = "ERRO NA ATUALIZAÇÃO DOS DADOS"
CORRECT_UPDATES_VALUES_USER = "PARAMETROS ATUALIZADOS CORRETAMENTE"

# Validation Errors
DATASET_ALREADY_EXISTS = "This Dataset Already Exists"
SUCCESS_DATASET_CREATION = "Dataset Criado com Sucesso"
PLEASE_FILL_FORM_CORRECTLY = "Please fill form correctly"
ERROR_ON_PREDICT = "Error during prediction of image"

# image size upload max length --> 20MB
MAX_IMAGE_SIZE = 20971520
SIZE_GREATER_TEMPORARY = 2621440
MAX_SIZE_OF_UPLOADED_MODEL = 100000000 # 100 mb